### ISSUE TITLE
MIT license certainly isn't compatible with Hunspell's license

### ISSUE THREAD

**Issue by Monkatraz** [zverok/spylls#13]
When I was [discussing linking to Espells from a few places](https://github.com/wooorm/nspell/issues/11#issuecomment-915802969) with the author of NSpell, they noted that Spylls likely is in violation of the Hunspell license.

Here is what they had to say:
> Spylls is explained as a “explanatory rewrite”, this sounds like carefully reading through the code and then implementing it either the same of a more clear way, and in the posts the Spyll author also explicitly mentions reading through the source and what they found there. That means it’s not 100% a new body of work. Which means it has to follow the MPL 1.1/GPL 2.0/LGPL 2.1 with copyright statement of Hunspell and add to it. So the first issue is there, and it’s a big one: spyll uses MIT, which is very permissive, whereas the author of Hunspell chose a strong license, to specifically prohibit such permissiveness. On top of that, it doesn’t acknowledge the copyright that the Hunspell author(s) have over their code

I had a vague notion of this issue, but made Espells MIT anyways. However, following this, I've relicensed it to MPL 2.0, which is allowed through the MPL license family that Hunspell is licensed under. I think MPL 2.0 is harmless for a repository like this, so that's what I would recommend.

**Comment by zverok** [comment]
Thanks for notifying me!
It is an important issue, and it just slipped my mind completely (I thought about it several times while working on the project in private, "dude, don't forget the licensing thing!"... and then, when I finished, I was so excited that I just forgot.)

It is my bad, and I'll be fixing it to MPL (and include extended notice about Hunspell authors copyright) next week; on the road currently.
