### ISSUE TITLE
Knob to fix word-case

### ISSUE THREAD

**Issue by doublex** [zverok/spylls#17]
I know you mentions this as design-goal, but is there a flag/knob to fix word-casing, e.g.:
`Walking` -> `walking`
Best wishes!

**Comment by zverok** [comment]
There is no flag for that currently, but probably there could be. Internally, there is enough information to provide it:
```ruby
from spylls.hunspell import Dictionary
# lookuper has a flag to know whether the word is correct including the right capitalization form:
dic.lookuper('Walking')                                                                                                                
#=> True
dic.lookuper('Walking', capitalization=False)                                                                                          
#=> False
dic.lookuper('walking', capitalization=False)                                                                                          
#=> True
```
So, we _might_ add just some parameter to suggest, which would be taken into consideration here: https://github.com/zverok/spylls/blob/master/spylls/hunspell/algo/suggest.py#L201 ...to tell the algorithm not to capitalize found correction :)

**Comment by doublex** [comment]
Thanks for your answer!
